### ISSUE TITLE
Testing things jdkfdj fkdj fdk

### ISSUE THREAD

**Issue by BrandonJoyce356** [BrandonJoyce356/specd-testing#37]
jfkdlsjfdksljkdl edit

**Comment by BrandonJoyce356** [comment]
test comment

**Comment by BrandonJoyce356** [comment]
Testing http://www.google.com

**Comment by BrandonJoyce356** [comment]
Test http://sonerdy.com

**Comment by BrandonJoyce356** [comment]
again http://sonerdy.com

**Comment by BrandonJoyce356** [comment]
and again http://sonerdy.com

**Comment by BrandonJoyce356** [comment]
Cool #37

**Comment by BrandonJoyce356** [comment]
![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2F19e03d8b-7f3e-4753-a7af-25ed716b29e9%2FBrandon2.gif)

**Comment by BrandonJoyce356** [comment]
![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2F5133069e-6cab-4e37-a732-accd2290c1fe%2FBrandon2.gif)

**Comment by BrandonJoyce356** [comment]
![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2F86305a09-a9df-4118-a680-e629a0d6f4d0%2FBrandon2.gif)

**Comment by BrandonJoyce356** [comment]
![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2Ff7273ca9-9a2a-40e9-9dd3-a1bbc4fe48d5%2FBrandon2.gif)

**Comment by BrandonJoyce356** [comment]
![AuYtq3tP.jpeg](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2Fffccad2a-3e79-489e-80bf-52c5e1d0f4d9%2FAuYtq3tP.jpeg)
 ![eb604a932b6d47f5a7f34a98b008bec3.jpeg](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2Fa04ac292-0f8c-4fda-a340-12b52f89c766%2Feb604a932b6d47f5a7f34a98b008bec3.jpeg)

**Comment by BrandonJoyce356** [comment]
![poet.png](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2Fb6fc16e0-8e25-4158-b98c-a25e2de30632%2Fpoet.png)
 ![Notifications-Idea.png](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-23%2F828adc52-f3af-4c55-a3b7-9110ac878f2e%2FNotifications-Idea.png)

**Comment by BrandonJoyce356** [comment]
![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-26%2F88ece6ea-57c1-4d3c-a41e-8515728359ae%2FBrandon2.gif)
 ![Brandon2.gif](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-03-26%2Ffc3b7867-a470-421d-b718-d6d9c168dea3%2FBrandon2.gif)

**Comment by BrandonJoyce356** [comment]
Test comment

**Comment by BrandonJoyce356** [comment]
![11210447_666184908527_6719039556054288698_n(2).jpg](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-05-29%2F91fb952a-f065-4285-afaa-c206e172868e%2F11210447_666184908527_6719039556054288698_n%282%29.jpg)

**Comment by baroldgene** [comment]
Best test image ever!

Thank you,
-Barry

**Comment by BrandonJoyce356** [comment]
Ha. Thanks!
