### ISSUE TITLE
too much cow bell

### ISSUE THREAD

**Issue by dapplebeforedawn** [BrandonJoyce356/specd-testing#60]
undefined
 ![Screen Shot 2015-04-04 at 12.08.05 AM.png](https://specd-dev-uploads.s3.amazonaws.com/comments%2F2015-04-04%2F5b75ee48-d0cf-4c77-abf3-3002a1f1b203%2FScreen+Shot+2015-04-04+at+12.08.05+AM.png)

**Comment by BrandonJoyce356** [comment]
Wow dude, haha.
